name: Joindate
version: '1.2'
description: Simple and lightweight joindate plugin with cache system.
author: Cherryh4ck
main: io.github.Cherryh4ck.joindate.Joindate
api-version: '1.21'
commands:
  joindate:
    description: "Shows player's joindate"
    usage: /joindate
    aliases: jd
  simplejd:
    description: "Plugin info & main command"
    usage: /simplejd
    permission: simplejd.main